[Date: 2018-06-18 11:46:58][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 12420]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 11:46:58][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 12420]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 11:46:59][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 12420]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:44:48][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:44:48][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:44:48][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:49:03][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:49:03][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:49:03][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:50:28][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "213.108.18.72", "ip_port": "53281", "ctime": 1529297428, "utime": 1529297428} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '213.108.18.72' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '213.108.18.72', 'ip_port': '53281', 'utime': 1529297428, 'ctime': 1529297428}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:50:48][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "163.44.165.165", "ip_port": "8080", "ctime": 1529297448, "utime": 1529297448} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '163.44.165.165' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '163.44.165.165', 'ip_port': '8080', 'utime': 1529297448, 'ctime': 1529297448}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:51:32][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "110.44.127.241", "ip_port": "8080", "ctime": 1529297492, "utime": 1529297492} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '110.44.127.241' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '110.44.127.241', 'ip_port': '8080', 'utime': 1529297492, 'ctime': 1529297492}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:51:32][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "60.205.224.143", "ip_port": "3128", "ctime": 1529297492, "utime": 1529297492} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '60.205.224.143' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '60.205.224.143', 'ip_port': '3128', 'utime': 1529297492, 'ctime': 1529297492}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:51:47][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "39.106.160.36", "ip_port": "3128", "ctime": 1529297507, "utime": 1529297507} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '39.106.160.36' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '39.106.160.36', 'ip_port': '3128', 'utime': 1529297507, 'ctime': 1529297507}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:53:17][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:53:17][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:53:17][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:54:49][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "58.221.72.185", "ip_port": "3128", "ctime": 1529297689, "utime": 1529297689} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '58.221.72.185' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '58.221.72.185', 'ip_port': '3128', 'utime': 1529297689, 'ctime': 1529297689}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:55:23][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "139.5.146.210", "ip_port": "3128", "ctime": 1529297723, "utime": 1529297723} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '139.5.146.210' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '139.5.146.210', 'ip_port': '3128', 'utime': 1529297723, 'ctime': 1529297723}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:55:51][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "66.70.147.196", "ip_port": "3128", "ctime": 1529297751, "utime": 1529297751} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '66.70.147.196' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '66.70.147.196', 'ip_port': '3128', 'utime': 1529297751, 'ctime': 1529297751}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:56:05][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "114.25.61.95", "ip_port": "53281", "ctime": 1529297765, "utime": 1529297765} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '114.25.61.95' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '114.25.61.95', 'ip_port': '53281', 'utime': 1529297765, 'ctime': 1529297765}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:56:06][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "5.9.178.178", "ip_port": "80", "ctime": 1529297766, "utime": 1529297766} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '5.9.178.178' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '5.9.178.178', 'ip_port': '80', 'utime': 1529297766, 'ctime': 1529297766}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:56:41][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "212.49.115.67", "ip_port": "8080", "ctime": 1529297801, "utime": 1529297801} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '212.49.115.67' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '212.49.115.67', 'ip_port': '8080', 'utime': 1529297801, 'ctime': 1529297801}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:57:33][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:57:33][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:57:33][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 18008]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 12:59:45][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "207.196.242.109", "ip_port": "80", "ctime": 1529297984, "utime": 1529297984} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '207.196.242.109' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '207.196.242.109', 'ip_port': '80', 'utime': 1529297984, 'ctime': 1529297984}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 12:59:46][Level: ERROR][File: logic_proxypool.py][LineNo: 48][Process: 18008]insert_into_proxypool fail.[ip_item]={"ip": "5.9.178.178", "ip_port": "80", "ctime": 1529297986, "utime": 1529297986} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '5.9.178.178' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '5.9.178.178', 'ip_port': '80', 'utime': 1529297986, 'ctime': 1529297986}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:35:24][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 21988]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:35:24][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 21988]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:35:24][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 21988]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:37:29][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 21988]insert_into_proxypool fail.[ip_item]={"ip": "119.28.152.208", "ip_port": "80", "ctime": 1529300249, "utime": 1529300249} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '119.28.152.208' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '119.28.152.208', 'ip_port': '80', 'utime': 1529300249, 'ctime': 1529300249}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:37:51][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 21988]insert_into_proxypool fail.[ip_item]={"ip": "167.99.227.82", "ip_port": "3128", "ctime": 1529300271, "utime": 1529300271} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '167.99.227.82' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '167.99.227.82', 'ip_port': '3128', 'utime': 1529300271, 'ctime': 1529300271}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:42:00][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:42:00][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:42:00][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:43:29][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "119.29.185.79", "ip_port": "8080", "ctime": 1529300609, "utime": 1529300609} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '119.29.185.79' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '119.29.185.79', 'ip_port': '8080', 'utime': 1529300609, 'ctime': 1529300609}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:43:31][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "178.150.19.69", "ip_port": "3128", "ctime": 1529300611, "utime": 1529300611} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '178.150.19.69' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '178.150.19.69', 'ip_port': '3128', 'utime': 1529300611, 'ctime': 1529300611}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:44:50][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:44:50][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:44:50][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:46:08][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "114.226.65.6", "ip_port": "6666", "ctime": 1529300768, "utime": 1529300768} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '114.226.65.6' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '114.226.65.6', 'ip_port': '6666', 'utime': 1529300768, 'ctime': 1529300768}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:46:19][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "121.231.226.221", "ip_port": "6666", "ctime": 1529300779, "utime": 1529300779} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '121.231.226.221' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '121.231.226.221', 'ip_port': '6666', 'utime': 1529300779, 'ctime': 1529300779}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:46:22][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "178.150.19.69", "ip_port": "3128", "ctime": 1529300782, "utime": 1529300782} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '178.150.19.69' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '178.150.19.69', 'ip_port': '3128', 'utime': 1529300782, 'ctime': 1529300782}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:46:38][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "31.173.209.111", "ip_port": "8080", "ctime": 1529300798, "utime": 1529300798} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '31.173.209.111' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '31.173.209.111', 'ip_port': '8080', 'utime': 1529300798, 'ctime': 1529300798}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:46:43][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "103.248.232.135", "ip_port": "8080", "ctime": 1529300803, "utime": 1529300803} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '103.248.232.135' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '103.248.232.135', 'ip_port': '8080', 'utime': 1529300803, 'ctime': 1529300803}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:46:56][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "119.29.185.79", "ip_port": "8080", "ctime": 1529300816, "utime": 1529300816} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '119.29.185.79' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '119.29.185.79', 'ip_port': '8080', 'utime': 1529300816, 'ctime': 1529300816}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:46:58][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "180.241.161.206", "ip_port": "8080", "ctime": 1529300818, "utime": 1529300818} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '180.241.161.206' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '180.241.161.206', 'ip_port': '8080', 'utime': 1529300818, 'ctime': 1529300818}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:47:26][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "14.118.255.8", "ip_port": "6666", "ctime": 1529300846, "utime": 1529300846} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '14.118.255.8' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '14.118.255.8', 'ip_port': '6666', 'utime': 1529300846, 'ctime': 1529300846}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:47:41][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:47:41][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:47:41][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 14060]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-06-18 13:49:20][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "119.29.185.79", "ip_port": "8080", "ctime": 1529300960, "utime": 1529300960} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '119.29.185.79' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '119.29.185.79', 'ip_port': '8080', 'utime': 1529300960, 'ctime': 1529300960}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:49:21][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "140.143.231.139", "ip_port": "80", "ctime": 1529300961, "utime": 1529300961} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '140.143.231.139' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '140.143.231.139', 'ip_port': '80', 'utime': 1529300961, 'ctime': 1529300961}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:49:33][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "103.248.232.135", "ip_port": "8080", "ctime": 1529300973, "utime": 1529300973} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '103.248.232.135' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '103.248.232.135', 'ip_port': '8080', 'utime': 1529300973, 'ctime': 1529300973}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:49:39][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "155.4.12.61", "ip_port": "8080", "ctime": 1529300979, "utime": 1529300979} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '155.4.12.61' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '155.4.12.61', 'ip_port': '8080', 'utime': 1529300979, 'ctime': 1529300979}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:49:43][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "178.150.19.69", "ip_port": "3128", "ctime": 1529300983, "utime": 1529300983} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '178.150.19.69' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '178.150.19.69', 'ip_port': '3128', 'utime': 1529300983, 'ctime': 1529300983}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:49:55][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "31.173.209.111", "ip_port": "8080", "ctime": 1529300994, "utime": 1529300994} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '31.173.209.111' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '31.173.209.111', 'ip_port': '8080', 'utime': 1529300994, 'ctime': 1529300994}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:51:43][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "94.16.117.29", "ip_port": "3128", "ctime": 1529301103, "utime": 1529301103} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '94.16.117.29' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '94.16.117.29', 'ip_port': '3128', 'utime': 1529301103, 'ctime': 1529301103}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:51:43][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "183.182.105.161", "ip_port": "3129", "ctime": 1529301103, "utime": 1529301103} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '183.182.105.161' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '183.182.105.161', 'ip_port': '3129', 'utime': 1529301103, 'ctime': 1529301103}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:53:14][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "88.199.147.0", "ip_port": "3128", "ctime": 1529301194, "utime": 1529301194} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '88.199.147.0' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '88.199.147.0', 'ip_port': '3128', 'utime': 1529301194, 'ctime': 1529301194}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:53:21][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "14.139.189.211", "ip_port": "3128", "ctime": 1529301201, "utime": 1529301201} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '14.139.189.211' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '14.139.189.211', 'ip_port': '3128', 'utime': 1529301201, 'ctime': 1529301201}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:53:22][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "218.60.8.98", "ip_port": "3129", "ctime": 1529301202, "utime": 1529301202} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '218.60.8.98' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '218.60.8.98', 'ip_port': '3129', 'utime': 1529301202, 'ctime': 1529301202}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:53:26][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "140.143.231.139", "ip_port": "80", "ctime": 1529301206, "utime": 1529301206} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '140.143.231.139' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '140.143.231.139', 'ip_port': '80', 'utime': 1529301206, 'ctime': 1529301206}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:55:14][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "218.60.8.98", "ip_port": "3129", "ctime": 1529301314, "utime": 1529301314} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '218.60.8.98' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '218.60.8.98', 'ip_port': '3129', 'utime': 1529301314, 'ctime': 1529301314}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:55:19][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "121.41.171.223", "ip_port": "3128", "ctime": 1529301319, "utime": 1529301319} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '121.41.171.223' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '121.41.171.223', 'ip_port': '3128', 'utime': 1529301319, 'ctime': 1529301319}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:55:22][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "58.221.72.185", "ip_port": "3128", "ctime": 1529301322, "utime": 1529301322} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '58.221.72.185' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '58.221.72.185', 'ip_port': '3128', 'utime': 1529301322, 'ctime': 1529301322}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-06-18 13:55:24][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 14060]insert_into_proxypool fail.[ip_item]={"ip": "123.163.132.33", "ip_port": "6666", "ctime": 1529301324, "utime": 1529301324} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '123.163.132.33' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '123.163.132.33', 'ip_port': '6666', 'utime': 1529301324, 'ctime': 1529301324}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-07-13 15:58:43][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 2228]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 15:58:44][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 2228]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 15:58:44][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 2228]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:03:09][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 2228]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:03:09][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 2228]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:03:09][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 2228]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:04:45][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 2228]insert_into_proxypool fail.[ip_item]={"ip": "197.211.32.134", "ip_port": "53281", "ctime": 1531469085, "utime": 1531469085} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '197.211.32.134' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '197.211.32.134', 'ip_port': '53281', 'utime': 1531469085, 'ctime': 1531469085}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-07-13 16:18:13][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 3844]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:18:13][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 3844]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:18:13][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 3844]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:22:45][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 3844]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:22:48][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 3844]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-13 16:22:51][Level: ERROR][File: spider_xicidaili.py][LineNo: 17][Process: 3844]Spider xicidaili error.[msg]='NoneType' object has no attribute 'find_all'
[Date: 2018-07-14 14:27:14][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 221792]insert_into_proxypool fail.[ip_item]={"ip": "49.79.156.130", "ip_port": "8000", "ctime": 1531549634, "utime": 1531549634} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '49.79.156.130' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '49.79.156.130', 'ip_port': '8000', 'utime': 1531549634, 'ctime': 1531549634}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-07-14 14:27:55][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 221792]insert_into_proxypool fail.[ip_item]={"ip": "118.31.220.3", "ip_port": "8080", "ctime": 1531549675, "utime": 1531549675} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '118.31.220.3' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '118.31.220.3', 'ip_port': '8080', 'utime': 1531549675, 'ctime': 1531549675}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-07-14 14:27:55][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 221792]insert_into_proxypool fail.[ip_item]={"ip": "49.79.156.109", "ip_port": "8000", "ctime": 1531549675, "utime": 1531549675} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '49.79.156.109' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '49.79.156.109', 'ip_port': '8000', 'utime': 1531549675, 'ctime': 1531549675}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Date: 2018-07-14 14:27:56][Level: ERROR][File: logic_proxypool.py][LineNo: 49][Process: 221792]insert_into_proxypool fail.[ip_item]={"ip": "114.97.184.89", "ip_port": "808", "ctime": 1531549676, "utime": 1531549676} [msg]=(pymysql.err.IntegrityError) (1062, "Duplicate entry '114.97.184.89' for key 'ip'") [SQL: 'INSERT INTO proxypool (ip, ip_port, utime, ctime) VALUES (%(ip)s, %(ip_port)s, %(utime)s, %(ctime)s)'] [parameters: {'ip': '114.97.184.89', 'ip_port': '808', 'utime': 1531549676, 'ctime': 1531549676}] (Background on this error at: http://sqlalche.me/e/gkpj)
